name: website

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: website-${{ github.head_ref }}
  cancel-in-progress: true

env:
  DEBUG: 1
  NODE_VERSION: "18.4.0"

jobs:
  build:
    name: Build
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm
        with:
          version: latest
          run_install: true
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      - name: Build
        run: pnpm run build